### ISSUE TITLE
Adding MATS to RNA-Seq pipeliner

### ISSUE THREAD

**Issue by pajailwala** [CCBR/Pipeliner#245]
Fathi, Vishal:
Lets plan to add MATS for detecting intron retention and other alternative splicing events from RNA-seq data:

http://rnaseq-mats.sourceforge.net/user_guide.htm

**Comment by kopardev** [comment]
Currently installed at /data/CCBR_Pipeliner/db/PipeDB/bin2/rMATS.3.2.5... testing!

**Comment by kopardev** [comment]
The -len parameter is required and takes only 1 value, i.e., expecting all reads to be of the same length. We cannot just push our trimmed reads or dmark.bams into it directly. Testing parsing raw fastqs.

**Comment by joshuabhk** [comment]
Yes. To properly run rMATS you need to start from the raw reads. And you
need to estimate the fragment size or some like that.
