### ISSUE TITLE
Could you add a ribosomal RNA content information 

### ISSUE THREAD

**Issue by joshuabhk** [CCBR/Pipeliner#263]
So that we can see in the Multiqc table.

**Comment by kopardev** [comment]
How do you calculate ribosomal RNA content?

**Comment by joshuabhk** [comment]
According to Maggie they are already calculated. She asked to put them into
multiqc. Thanks.

**Comment by kopardev** [comment]
Hmm. I dont know. I will have to find out.
@pajailwala used in a recent project. Does he know where?
--Vishal

**Comment by pajailwala** [comment]
Vishal:

For my project, I didn’t actually use a rRNA intervals list. What I did was to filter out all rRNAs that were the source of a 90% GC-peak on the GC distribution (I filtered for reads mapping to a single locus rDNA that gives rise to various rRNAs).

For our pipeline, we are assessing (not filtering for) rRNA contamination. Essentially, for any gtf file that has the standard ‘gene_type’ column, the rRNA intervals are created by grepping for ‘rRNA’ on the gene_type.
Here is someone’s script that we can use to create the rRNA-intervals list (BED format) for all the GTF files used in our pipeline:
https://gist.github.com/adomingues/57e3c2f9f4aca8dfde7b

Does that help?

Thanks,
Parthav

**Comment by joshuabhk** [comment]
Hi Parthav,

I need to double check with Maggie, but I thought she was mentioning Picard RNASeqMetrics. Don't we have the RNAseqMetrics calculated in the pipeline?

Bong-Hyun

**Comment by kopardev** [comment]
Yes. Bong-Hyun, it does seem to report it.
https://broadinstitute.github.io/picard/picard-metric-definitions.html#RnaSeqMetrics
--Vishal

**Comment by pajailwala** [comment]
My understanding is that rRNA metrics will only be reported by CollectRnaSeqMetrics, if the rRNA intervals file is passed to RIBOSOMAL_INTERVALS parameter.

In our RNASeq QC pipeline, I think we do assess rRNA metrics, but they are reported as part of the excel file (SF format). Still, we need to ensure that the ribosomal intervals file is accurate (based on the respective GTF that is used) and also see if we can have multiQC parse these metrics.

java -jar picard.jar CollectRnaSeqMetrics \
      I=input.bam \
      O=output.RNA_Metrics \
      REF_FLAT=ref_flat.txt \
      STRAND=SECOND_READ_TRANSCRIPTION_STRAND \
      RIBOSOMAL_INTERVALS=ribosomal.interval_list

**Comment by kopardev** [comment]
Yes Parthav, 

Thats right. We do have RIBOSOMAL_BASES showing number of RNA bases covered in the bam file. and it is dependent on the RRNALIST provided, which generally are : 

- "/data/CCBR_Pipeliner/db/PipeDB/dev/Hg19.rRNA.interval_list_v3"
- "/data/CCBR_Pipeliner/db/PipeDB/dev/Hg38.rRNA.interval_list_R26" and
- "/data/CCBR_Pipeliner/db/PipeDB/dev/Mm10.rRNA.interval_list_M12".

As per picard,

RIBOSOMAL_BASES --> Number of bases in primary alignments that align to ribosomal sequence.

This to me only indicates if the rDNA bases that are covered by sequencing, but does not give any idea about the depth at these bases. I think one is going to have some coverage over these bases, no matter what. It is how often they are covered that is important to us. Isnt it?

--Vishal

**Comment by vnkoparde** [comment]
Added  rRNA index in FqScreen. This close #263
