### ISSUE TITLE
Redesign DEG folders

### ISSUE THREAD

**Issue by kopardev** [CCBR/Pipeliner#324]
- Need to add an extra column to "contrasts.tab", which will serve as an CPM cutoff threshold for the contrast represented on that line in the file.

- all sample DEG folder separate (generated during initialQC)

- DEG_RSEM_genes_<contrast>_<CPM_threshold> as folder name of each contrast. 
   --filter each contrasts separtely
   --create separate PCA of contrast-only groups

**Comment by skchronicles** [comment]
Additions have been added to activeDev (two new columns are required for contrasts.txt)
New format goes like:
grp1    grp2    cpmThreshold    minSampleThreshold

Example:
KO	WT	0.5	2
KO	WT	0.5	1

Creates the following DE directories:
DEG_KO-WT_0.5_2/
DEG_KO-WT_0.5_2/
