### ISSUE TITLE
RNA-seq problem:   Error in rule trim_pe:

### ISSUE THREAD

**Issue by yuguoyun** [CCBR/Pipeliner#402]
I was trying run the rnaseq module, and it couldn't finish due to this error:
What could be the problem. The directory is there.

[Mon Feb  4 13:12:19 2019] 7 of 113 steps (6%) done
[Mon Feb  4 13:12:57 2019]     Error in rule trim_pe:
[Mon Feb  4 13:12:57 2019]         jobid: 85
[Mon Feb  4 13:12:57 2019]         output: 
working/trim/SAMPLE10_WB_R1_001_trim_paired.fastq.gz, working/trim/SAMPLE10_WB_R1_001_trim_unpaired.fastq.gz, working/trim/SAMPLE10_WB_R2_001_trim_paired.fastq.gz, working/trim/SAMPLE10_WB_R2_001_trim_unpaired.fastq.gz, working/QC/SAMPLE10_WB_run_trimmomatic.err

 Reports]$ more working/QC/SAMPLE10_WB_run_trimmomatic.err
working/QC/SAMPLE10_WB_run_trimmomatic.err: No such file or directory

**Comment by skchronicles** [comment]
### RNA-seq: Error in rule trim_pe
@yuguoyun, can you verify that your sample names match the following pattern?
 - `*.R?.fastq.gz`

If not, you will need to rename your samples:
 - `<samplename>.R1.fastq.gz`  &&  `<samplename>.R2.fastq.gz`  

Please check out our wiki for more detailed information:
https://github.com/CCBR/Pipeliner/wiki/2.-RNA-Seq-Gene-Expression-Pipeline-Documentation#running-the-rnaseq-pipeline

**Comment by yuguoyun** [comment]
Thank you,Skyler. I think I figured it out. I run out of space.Guoyun (George) YuSent from my phone
-------- Original message --------From: Skyler Kuhn <notifications@github.com> Date: 2/6/19  7:25 PM  (GMT-05:00) To: CCBR/Pipeliner <Pipeliner@noreply.github.com> Cc: yuguoyun <yuguoyun@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [CCBR/Pipeliner] RNA-seq problem:   Error in rule trim_pe: (#402) RNA-seq: Error in rule trim_pe
@yuguoyun, can you verify that your sample names match the following pattern?

*.R?.fastq.gz

If not, you will need to rename your samples:

<samplename>.R1.fastq.gz  &&  <samplename>.R2.fastq.gz

Please check out our wiki for more detailed information:
https://github.com/CCBR/Pipeliner/wiki/2.-RNA-Seq-Gene-Expression-Pipeline-Documentation#running-the-rnaseq-pipeline

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CCBR/Pipeliner","title":"CCBR/Pipeliner","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/CCBR/Pipeliner"}},"updates":{"snippets":[{"icon":"PERSON","message":"@skchronicles in #402: ### RNA-seq: Error in rule trim_pe\r\n@yuguoyun, can you verify that your sample names match the following pattern?\r\n - `*.R?.fastq.gz`\r\n\r\nIf not, you will need to rename your samples:\r\n - `\u003csamplename\u003e.R1.fastq.gz`  \u0026\u0026  `\u003csamplename\u003e.R2.fastq.gz`  \r\n\r\nPlease check out our wiki for more detailed information:\r\nhttps://github.com/CCBR/Pipeliner/wiki/2.-RNA-Seq-Gene-Expression-Pipeline-Documentation#running-the-rnaseq-pipeline\r\n"}],"action":{"name":"View Issue","url":"https://github.com/CCBR/Pipeliner/issues/402#issuecomment-461242905"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CCBR/Pipeliner/issues/402#issuecomment-461242905",
"url": "https://github.com/CCBR/Pipeliner/issues/402#issuecomment-461242905",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
