### ISSUE TITLE
Variant Calling for RNAseq (hg38) stopped at star_align_2 

### ISSUE THREAD

**Issue by tangwei1129** [CCBR/Pipeliner#464]
I tried to run RNA-seq analysis on hg38 for variant calling option, and it stopped at star_align_2, and gave errors see below. please advice me what to do. Thx.
Wei 
NCI/NIH

[Fri Jun 11 19:59:52 2021]     Error in rule star_align_2:
[Fri Jun 11 19:59:52 2021]         jobid: 0
[Fri Jun 11 19:59:52 2021]         output: SL477789.p2Aligned.out.bam, SL477789.p2SJ.out.tab, SL477789.p2Log.final.out

[Fri Jun 11 19:59:52 2021] RuleException:
[Fri Jun 11 19:59:52 2021] CalledProcessError in line 13 of /data/CCBR_Pipeliner/4.0.2/Pipeliner/Rules/star.align.2.rl:

**Comment by skchronicles** [comment]
Hello @tangwei1129, 

Thank you for reaching out to us. Can you please attach the "HPC_usage_table.txt" in the output directory of the pipeline? I have a feeling the prior step may have failed due to the number of splice junctions it is trying to insert into the genome. Can you also look through one of the slurm output files for rule star_align_2 to see if it is reporting this error message:

> EXITING because of FATAL ERROR: cannot insert junctions on the fly because of strand GstrandBit problem
> SOLUTION: please contact STAR author at https://groups.google.com/forum/#!forum/rna-star

Regards,
@skchronicles

**Comment by tangwei1129** [comment]
I have attached the HPC_usage_table.txt, and also found the error you mentioned. see below. How can I fix it?
'EXITING because of FATAL ERROR: cannot insert junctions on the fly because of strand GstrandBit problem
Jun 12 00:18:19 ...... FATAL ERROR, exiting'

[HPC_usage_table.txt](https://github.com/CCBR/Pipeliner/files/6652065/HPC_usage_table.txt)

**Comment by skchronicles** [comment]
Hey @tangwei1129, 
 
Yes, it is failing due to the number of splice junctions it is attempting to insert back into the reference genome. I have seen this issue occur once before and thought it was a one-off, sample specific issue . I will push a permanent fix to the activeDev branch of Pipeliner when I get some free time today or tomorrow. 

I will keep you in the loop, and I will let you know when you can re-run the pipeline with the latest changes.

**Comment by skchronicles** [comment]
Hey @tangwei1129,

I have pulled in a patch 9febecd52bb594b6e60bd7563c9efb56f23f0029 into Biowulf.

Can you please re-try running Pipeliner's RNA variant calling pipeline with module 4.0.2 on Biowulf? 

```bash
module purge
module load ccbrpipeliner/4.0.2
ccbrpipe.sh
```

When the GUI pops up, please point to a new working directory. Do not point to the same output directory in the previous failed run. This will ensure that the new resources containing the patch get carried over.

![image](https://user-images.githubusercontent.com/18038345/122294134-be35ad00-cec5-11eb-84cb-e59120f1b1ea.png)

Thank you for testing this out on your side, and please let me know if there are any issues.

**Comment by tangwei1129** [comment]
it seems I can not initialize the directory. it says Permission denied.
copying template into /data/tangw3/rnaseqSV1
cp: cannot open
‘/gpfs/gsfs5/users/CCBR_Pipeliner/4.0.2/Pipeliner/Results-template/Scripts/jaccard_score.py’
for reading: Permission denied
cp: cannot open
‘/gpfs/gsfs5/users/CCBR_Pipeliner/4.0.2/Pipeliner/Results-template/Scripts/bam_filter_by_mapq.py’
for reading: Permission denied
cp: cannot open
‘/gpfs/gsfs5/users/CCBR_Pipeliner/4.0.2/Pipeliner/Results-template/Scripts/scrnaQC.Rmd’
for reading: Permission denied
cp: cannot open
‘/gpfs/gsfs5/users/CCBR_Pipeliner/4.0.2/Pipeliner/Results-template/Scripts/scrnaQC.R’
for reading: Permission denied


Skyler Kuhn ***@***.***> 于2021年6月16日周三 下午5:12写道：

**Comment by kopardev** [comment]
@skchronicles can you please reset permissions like this:
`chmod -R a+rX /data/CCBR_Pipeliner/4.0.2/Pipeliner/Results-template/Scripts`. Even I don't have permission to change these permissions.

**Comment by skchronicles** [comment]
@tangwei1129 Sorry about that, when I pulled the patch onto the Biowulf, I forgot to update permissions for other. 

I have corrected the issue. Please try re-run Pipeliner again. You shouldn't have any issues copying over the files into your working directory.

**Comment by tangwei1129** [comment]
it still has a problem with the initial directory. see below. and dry run
could not start either.
copying template into /data/tangw3/SV
cp: cannot open
‘/gpfs/gsfs5/users/CCBR_Pipeliner/4.0.2/Pipeliner/Results-template/Scripts/.kopardevn_dir_bash_history’
for reading: Permission denied

Skyler Kuhn ***@***.***> 于2021年6月17日周四 上午9:55写道：

**Comment by tangwei1129** [comment]
I tried, and now it stopped after alignment. see below error.

859 of 6505 steps (13%) done
[Thu Jun 17 15:00:14 2021] Removing temporary output file
SL477774Aligned.out.bam.
[Thu Jun 17 15:00:14 2021] Failed to remove marker file for job started
([Errno 2] No such file or directory: 'SL477774Aligned.out.bam'). Please
ensure write permissions for the directory
/gpfs/gsfs12/users/tangw3/hudsonalpha/haib20CY6295/RNA/SV/.snakemake
[Thu Jun 17 15:00:14 2021] Finished job 6434.
[Thu Jun 17 15:00:14 2021] 860 of 6505 steps (13%) done
[Thu Jun 17 15:00:24 2021] Exiting because a job execution failed. Look
above for error message
[Thu Jun 17 15:00:24 2021] Complete log:
/gpfs/gsfs12/users/tangw3/hudsonalpha/haib20CY6295/RNA/SV/.snakemake/log/2021-06-17T130927.374495.snakemake.log

Vishal Koparde ***@***.***> 于2021年6月17日周四 上午11:55写道：

**Comment by skchronicles** [comment]
@tangwei1129 Can you please send us the pipeline's new "HPC_usage_table.txt"?

**Comment by tangwei1129** [comment]
yes sure. please see the attached.
or the last couple lines of file 
pl:star1p	17293561	ccr	FAILED	1	32	4-00:00:00	00:00:17	96.0GB/node	0.0GB	cn2299	1	152	0.151111	ambss	tangw3
pl:star1p	17293733	ccr	FAILED	1	32	4-00:00:00	00:00:19	96.0GB/node	0.0GB	cn2314	1	147	0.168889	ambss	tangw3
pl:star1p	17293753	ccr	FAILED	1	32	4-00:00:00	00:00:14	96.0GB/node	0.0GB	cn2413		144	0.124444	ambss	tangw3
pl:star1p	17293754	ccr	FAILED	1	32	4-00:00:00	00:00:17	96.0GB/node	0.0GB	cn4474	1	139	0.151111	ambss	tangw3
pl:star1p	17293757	ccr	COMPLETED	1	32	4-00:00:00	00:19:35	96.0GB/node	34.3GB	cn2286	16	339	10.444445	ambss	tangw3
pl:star1p	17293786	ccr	FAILED	1	32	4-00:00:00	00:00:26	96.0GB/node	0.0GB	cn2299	1	253	0.231111	ambss	tangw3
pl:star1p	17293788	ccr	FAILED	1	32	4-00:00:00	00:03:41	96.0GB/node	0.0GB	cn2304	2	251	1.964444	ambss	tangw3
pl:star1p	17293941	ccr	FAILED	1	32	4-00:00:00	00:00:25	96.0GB/node	0.0GB	cn2314	1	151	0.222222	ambss	tangw3
pl:star1p	17293974	ccr	FAILED	1	32	4-00:00:00	00:00:23	96.0GB/node	0.0GB	cn2413		57	0.204444	ambss	tangw3
pl:star1p	17293977	ccr	FAILED	1	32	4-00:00:00	00:00:26	96.0GB/node	0.0GB	cn4474	1	54	0.231111	ambss	tangw3

[HPC_usage_table.txt](https://github.com/CCBR/Pipeliner/files/6677777/HPC_usage_table.txt)

**Comment by skchronicles** [comment]
@tangwei1129 Can we close this issue? I believe the changes we made to a local clone of Pipeliner on Biowulf addressed these issues (i.e. running STAR in a per sample 2-pass basic mode).

**Comment by tangwei1129** [comment]
yes, please close it.
Thank you so much for your help!

Skyler Kuhn ***@***.***> 于2021年7月1日周四 上午10:41写道：

**Comment by skchronicles** [comment]
Sounds good, have a great 4th of the July weekend @tangwei1129!
