### ISSUE TITLE
PIM not working for custom genome 

### ISSUE THREAD

**Issue by ky66** [CCBR/Pipeliner#473]
I used the PIM tool to generate reference files for my custom genome that is not listed in the CCBR pipeliner GUI. PIM failed for my FASTA and GTF and I cannot pinpoint what the exact problem is with PIM. How can I troubleshoot here?

Thanks

**Comment by skchronicles** [comment]
Duplicated issue, see issue https://github.com/CCBR/Pipeliner/issues/471 for continued discussion and more information.
