### ISSUE TITLE
Genome.json file error with pipeliner v4.0.2

### ISSUE THREAD

**Issue by slsevilla** [CCBR/Pipeliner#475]
After loading the default version of Pipeliner (v4.0.2),I ran into the following error (running RNASeq, hg19, Quality Control Analysis):

```
Checking for 'counts/' directory...
Drying-running: RNAseq
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Anaconda/envs/py3.5/lib/python3.5/tkinter/__init__.py", line 1558, in __call__
    return self.func(*args)
  File "/gpfs/gsfs10/users/CCBR_Pipeliner/4.0.2/Pipeliner/gui/frame.py", line 771, in dryrun
    self.makejson("none")
  File "/gpfs/gsfs10/users/CCBR_Pipeliner/4.0.2/Pipeliner/gui/rnaseq.py", line 378, in makejson
    ), "r"
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/gsfs10/users/CCBR_Pipeliner/4.0.2/Pipeliner/Select the genome.json'
```

I wasn't able to figure out why the genome.json variable isn't being interpreted here, but after deleting the dir and running with v4.0, I was able to get the pipeline to run.

For troubleshooting info:
- raw dir:  /data/CCBR/rawdata/ccbr1199/GSE118014/fastq/ 
- output dir: /data/CCBR/projects/ccbr1199/GSE118014/pipelinerqc_20220830

**Comment by skchronicles** [comment]
@slsevilla Can you reproduce the error and take a screenshot of the gui when this occurs? I cannot tell if this is an error with the X11 connection, or if a genome was not selected from the drop down. 

Best,
@skchronicles 

Best

**Comment by slsevilla** [comment]
Just attempted to re-create and I'm not getting the issue. I'm sure it wasn't an issue with selecting the genome - @phoman14 (Phil) originally had the issue and asked me to troubleshoot. I was able to re-create it on my own system multiple times. Perhaps it was a connection issue - that would explain why we were both seeing it then, but not now.

Either way, seems to be resolved, so OK to close the issue. Will reopen if we see this again.

**Comment by skchronicles** [comment]
Okay, that sounds good. Thank you for looking into this more!
